port_profiles:
  - profile: PP-DOT1X
    mode: "trunk phone"
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    dot1x:
      port_control: auto
      reauthentication: true
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3


network_ports:
# ---------------- IDF1 ----------------
  - switches:
      - leaf-1[ab]    # regex match LEAF-1a & LEAF-1b
    switch_ports:
      # - Ethernet1-48
      - Ethernet1
    description: IDF1 dot1x port
    profile: PP-DOT1X
    native_vlan: 110
    structured_config:
      phone:
        trunk: untagged
        vlan: 120
    dot1x:
      authentication_failure:
        action: allow
        allow_vlan: 130
# ---------------- IDF2 ----------------
  # - switches:
  #     - leaf-2a
  #   switch_ports:
  #     # - Ethernet1-48
  #     - Ethernet1
  #   description: IDF2 dot1x port
  #   profile: PP-DOT1X
  #   native_vlan: 210
  #   structured_config:
  #     phone:
  #       trunk: untagged
  #       vlan: 220
  #   dot1x:
  #     authentication_failure:
  #       action: allow
  #       allow_vlan: 230
