tenants:
  - name: CAMPUS_SERVICES
    vrfs:
      - name: default
        svis:
          - id: 110
            name: 'IDF1-Data'
            # tags: ["110"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.10.1
            nodes:
              - node: SPINE1
                ip_address: 10.1.10.2/23
              - node: SPINE2
                ip_address: 10.1.10.3/23
          - id: 210
            name: 'IDF2-Data'
            # tags: ["210"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.10.1
            nodes:
              - node: SPINE1
                ip_address: 10.1.10.2/23
              - node: SPINE2
                ip_address: 10.1.10.3/23
          # - id: 120
          #   name: 'IDF1-Voice'
          #   tags: ["120"]
          #   enabled: true
          #   ip_virtual_router_addresses:
          #     - 10.1.20.1
          #   nodes:
          #     - node: SPINE1
          #       ip_address: 10.1.20.2/23
          #     - node: SPINE2
          #       ip_address: 10.1.20.3/23