##############################################
# RUN CI on PR / PUSH EVENT
##############################################
kind: pipeline
type: docker
name: atd-avd-campus-ci

trigger:
  event:
    - push
    - pull_request

steps:
  - name: install-and-build-configurations
    #image: python:3.11
    image: git.as73.inetsix.net/inetsix-configs/ansible-runner:latest
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - ansible-galaxy collection install --force -r galaxy.yml
      - pip3 install -r /root/.ansible/collections/ansible_collections/arista/avd/requirements.txt
      - ansible-playbook playbooks/atd-fabric-build.yml
