---
- name: Provision ATD environment to prepare AVD Lab
  hosts: CV_SERVERS
  connection: local
  gather_facts: false
  vars:
    execute_tasks: true
  tasks:
    - name: Run AVD Provisioner
      import_role:
        name: 'atd_provisioner'
