---
- name: Configuration deployment with CVP
  hosts: CV_SERVERS
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Provision CVP with AVD configuration
      import_role:
        name: eos_config_deploy_cvp
      vars:
        container_root: 'CAMPUS'
        configlets_prefix: 'AVD_CAMPUS_'
        state: present
